namespace QLKDD.GUI
{
    partial class frmKhachHang
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmKhachHang));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.txttimkiem = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btntracuu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.rdsanxuat = new System.Windows.Forms.RadioButton();
            this.rdsinhhoat = new System.Windows.Forms.RadioButton();
            this.txtdiachi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtsdt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txttenkh = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtmakh = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnhuy = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnsua = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnxoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnluu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnthem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lvds = new System.Windows.Forms.ListView();
            this.columnHeader1 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader2 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader3 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader4 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader5 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.panel1.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(115)))), ((int)(((byte)(109)))), ((int)(((byte)(155)))));
            this.panel1.Controls.Add(this.txttimkiem);
            this.panel1.Controls.Add(this.btntracuu);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1115, 100);
            this.panel1.TabIndex = 0;
            // 
            // txttimkiem
            // 
            this.txttimkiem.AcceptsReturn = false;
            this.txttimkiem.AcceptsTab = false;
            this.txttimkiem.AnimationSpeed = 200;
            this.txttimkiem.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txttimkiem.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txttimkiem.BackColor = System.Drawing.Color.Transparent;
            this.txttimkiem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txttimkiem.BackgroundImage")));
            this.txttimkiem.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txttimkiem.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txttimkiem.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txttimkiem.BorderColorIdle = System.Drawing.Color.Silver;
            this.txttimkiem.BorderRadius = 10;
            this.txttimkiem.BorderThickness = 1;
            this.txttimkiem.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txttimkiem.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txttimkiem.DefaultFont = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txttimkiem.DefaultText = "";
            this.txttimkiem.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(115)))), ((int)(((byte)(109)))), ((int)(((byte)(155)))));
            this.txttimkiem.ForeColor = System.Drawing.Color.White;
            this.txttimkiem.HideSelection = true;
            this.txttimkiem.IconLeft = null;
            this.txttimkiem.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txttimkiem.IconPadding = 10;
            this.txttimkiem.IconRight = null;
            this.txttimkiem.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txttimkiem.Lines = new string[0];
            this.txttimkiem.Location = new System.Drawing.Point(717, 29);
            this.txttimkiem.MaxLength = 32767;
            this.txttimkiem.MinimumSize = new System.Drawing.Size(1, 1);
            this.txttimkiem.Modified = false;
            this.txttimkiem.Multiline = false;
            this.txttimkiem.Name = "txttimkiem";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttimkiem.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txttimkiem.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttimkiem.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(115)))), ((int)(((byte)(109)))), ((int)(((byte)(155)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttimkiem.OnIdleState = stateProperties24;
            this.txttimkiem.Padding = new System.Windows.Forms.Padding(3);
            this.txttimkiem.PasswordChar = '\0';
            this.txttimkiem.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txttimkiem.PlaceholderText = "Cần tìm khách hàng?";
            this.txttimkiem.ReadOnly = false;
            this.txttimkiem.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txttimkiem.SelectedText = "";
            this.txttimkiem.SelectionLength = 0;
            this.txttimkiem.SelectionStart = 0;
            this.txttimkiem.ShortcutsEnabled = true;
            this.txttimkiem.Size = new System.Drawing.Size(260, 40);
            this.txttimkiem.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txttimkiem.TabIndex = 4;
            this.txttimkiem.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txttimkiem.TextMarginBottom = 0;
            this.txttimkiem.TextMarginLeft = 3;
            this.txttimkiem.TextMarginTop = 0;
            this.txttimkiem.TextPlaceholder = "Cần tìm khách hàng?";
            this.txttimkiem.UseSystemPasswordChar = false;
            this.txttimkiem.WordWrap = true;
            // 
            // btntracuu
            // 
            this.btntracuu.AllowAnimations = true;
            this.btntracuu.AllowMouseEffects = true;
            this.btntracuu.AllowToggling = false;
            this.btntracuu.AnimationSpeed = 200;
            this.btntracuu.AutoGenerateColors = false;
            this.btntracuu.AutoRoundBorders = false;
            this.btntracuu.AutoSizeLeftIcon = true;
            this.btntracuu.AutoSizeRightIcon = true;
            this.btntracuu.BackColor = System.Drawing.Color.Transparent;
            this.btntracuu.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btntracuu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btntracuu.BackgroundImage")));
            this.btntracuu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btntracuu.ButtonText = "TRA CỨU";
            this.btntracuu.ButtonTextMarginLeft = 0;
            this.btntracuu.ColorContrastOnClick = 45;
            this.btntracuu.ColorContrastOnHover = 45;
            this.btntracuu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btntracuu.CustomizableEdges = borderEdges7;
            this.btntracuu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btntracuu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btntracuu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btntracuu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btntracuu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btntracuu.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btntracuu.ForeColor = System.Drawing.Color.White;
            this.btntracuu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btntracuu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btntracuu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btntracuu.IconMarginLeft = 11;
            this.btntracuu.IconPadding = 10;
            this.btntracuu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btntracuu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btntracuu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btntracuu.IconSize = 25;
            this.btntracuu.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btntracuu.IdleBorderRadius = 10;
            this.btntracuu.IdleBorderThickness = 1;
            this.btntracuu.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btntracuu.IdleIconLeftImage = null;
            this.btntracuu.IdleIconRightImage = null;
            this.btntracuu.IndicateFocus = false;
            this.btntracuu.Location = new System.Drawing.Point(983, 32);
            this.btntracuu.Name = "btntracuu";
            this.btntracuu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btntracuu.OnDisabledState.BorderRadius = 10;
            this.btntracuu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btntracuu.OnDisabledState.BorderThickness = 1;
            this.btntracuu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btntracuu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btntracuu.OnDisabledState.IconLeftImage = null;
            this.btntracuu.OnDisabledState.IconRightImage = null;
            this.btntracuu.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btntracuu.onHoverState.BorderRadius = 10;
            this.btntracuu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btntracuu.onHoverState.BorderThickness = 1;
            this.btntracuu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btntracuu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btntracuu.onHoverState.IconLeftImage = null;
            this.btntracuu.onHoverState.IconRightImage = null;
            this.btntracuu.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btntracuu.OnIdleState.BorderRadius = 10;
            this.btntracuu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btntracuu.OnIdleState.BorderThickness = 1;
            this.btntracuu.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btntracuu.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btntracuu.OnIdleState.IconLeftImage = null;
            this.btntracuu.OnIdleState.IconRightImage = null;
            this.btntracuu.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btntracuu.OnPressedState.BorderRadius = 10;
            this.btntracuu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btntracuu.OnPressedState.BorderThickness = 1;
            this.btntracuu.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btntracuu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btntracuu.OnPressedState.IconLeftImage = null;
            this.btntracuu.OnPressedState.IconRightImage = null;
            this.btntracuu.Size = new System.Drawing.Size(100, 35);
            this.btntracuu.TabIndex = 3;
            this.btntracuu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btntracuu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btntracuu.TextMarginLeft = 0;
            this.btntracuu.TextPadding = new System.Windows.Forms.Padding(0);
            this.btntracuu.UseDefaultRadiusAndThickness = true;
            this.btntracuu.Click += new System.EventHandler(this.btntracuu_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.White;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.rdsanxuat);
            this.bunifuPanel1.Controls.Add(this.rdsinhhoat);
            this.bunifuPanel1.Controls.Add(this.txtdiachi);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel6);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel5);
            this.bunifuPanel1.Controls.Add(this.txtsdt);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Controls.Add(this.txttenkh);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.txtmakh);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Location = new System.Drawing.Point(12, 106);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1091, 207);
            this.bunifuPanel1.TabIndex = 1;
            // 
            // rdsanxuat
            // 
            this.rdsanxuat.AutoSize = true;
            this.rdsanxuat.Font = new System.Drawing.Font("Calibri", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdsanxuat.ForeColor = System.Drawing.Color.White;
            this.rdsanxuat.Location = new System.Drawing.Point(913, 38);
            this.rdsanxuat.Name = "rdsanxuat";
            this.rdsanxuat.Size = new System.Drawing.Size(88, 25);
            this.rdsanxuat.TabIndex = 20;
            this.rdsanxuat.TabStop = true;
            this.rdsanxuat.Text = "Sản xuất";
            this.rdsanxuat.UseVisualStyleBackColor = true;
            // 
            // rdsinhhoat
            // 
            this.rdsinhhoat.AutoSize = true;
            this.rdsinhhoat.Font = new System.Drawing.Font("Calibri", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rdsinhhoat.ForeColor = System.Drawing.Color.White;
            this.rdsinhhoat.Location = new System.Drawing.Point(767, 38);
            this.rdsinhhoat.Name = "rdsinhhoat";
            this.rdsinhhoat.Size = new System.Drawing.Size(94, 25);
            this.rdsinhhoat.TabIndex = 19;
            this.rdsinhhoat.TabStop = true;
            this.rdsinhhoat.Text = "Sinh hoạt";
            this.rdsinhhoat.UseVisualStyleBackColor = true;
            // 
            // txtdiachi
            // 
            this.txtdiachi.AcceptsReturn = false;
            this.txtdiachi.AcceptsTab = false;
            this.txtdiachi.AnimationSpeed = 200;
            this.txtdiachi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtdiachi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtdiachi.BackColor = System.Drawing.Color.Transparent;
            this.txtdiachi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtdiachi.BackgroundImage")));
            this.txtdiachi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtdiachi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtdiachi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtdiachi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtdiachi.BorderRadius = 1;
            this.txtdiachi.BorderThickness = 1;
            this.txtdiachi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtdiachi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdiachi.DefaultFont = new System.Drawing.Font("Calibri", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtdiachi.DefaultText = "";
            this.txtdiachi.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.txtdiachi.ForeColor = System.Drawing.Color.White;
            this.txtdiachi.HideSelection = true;
            this.txtdiachi.IconLeft = null;
            this.txtdiachi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdiachi.IconPadding = 10;
            this.txtdiachi.IconRight = null;
            this.txtdiachi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdiachi.Lines = new string[0];
            this.txtdiachi.Location = new System.Drawing.Point(741, 93);
            this.txtdiachi.MaxLength = 32767;
            this.txtdiachi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtdiachi.Modified = false;
            this.txtdiachi.Multiline = false;
            this.txtdiachi.Name = "txtdiachi";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdiachi.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtdiachi.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdiachi.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            stateProperties28.ForeColor = System.Drawing.Color.White;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdiachi.OnIdleState = stateProperties28;
            this.txtdiachi.Padding = new System.Windows.Forms.Padding(3);
            this.txtdiachi.PasswordChar = '\0';
            this.txtdiachi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtdiachi.PlaceholderText = "";
            this.txtdiachi.ReadOnly = false;
            this.txtdiachi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtdiachi.SelectedText = "";
            this.txtdiachi.SelectionLength = 0;
            this.txtdiachi.SelectionStart = 0;
            this.txtdiachi.ShortcutsEnabled = true;
            this.txtdiachi.Size = new System.Drawing.Size(260, 39);
            this.txtdiachi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtdiachi.TabIndex = 18;
            this.txtdiachi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtdiachi.TextMarginBottom = 0;
            this.txtdiachi.TextMarginLeft = 3;
            this.txtdiachi.TextMarginTop = 0;
            this.txtdiachi.TextPlaceholder = "";
            this.txtdiachi.UseSystemPasswordChar = false;
            this.txtdiachi.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Calibri", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel6.Location = new System.Drawing.Point(660, 99);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(54, 21);
            this.bunifuLabel6.TabIndex = 17;
            this.bunifuLabel6.Text = "Địa Chỉ:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Calibri", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel5.Location = new System.Drawing.Point(681, 38);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(33, 21);
            this.bunifuLabel5.TabIndex = 16;
            this.bunifuLabel5.Text = "Loại:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtsdt
            // 
            this.txtsdt.AcceptsReturn = false;
            this.txtsdt.AcceptsTab = false;
            this.txtsdt.AnimationSpeed = 200;
            this.txtsdt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtsdt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtsdt.BackColor = System.Drawing.Color.Transparent;
            this.txtsdt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtsdt.BackgroundImage")));
            this.txtsdt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtsdt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtsdt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtsdt.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtsdt.BorderRadius = 1;
            this.txtsdt.BorderThickness = 1;
            this.txtsdt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtsdt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsdt.DefaultFont = new System.Drawing.Font("Calibri", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtsdt.DefaultText = "";
            this.txtsdt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.txtsdt.ForeColor = System.Drawing.Color.White;
            this.txtsdt.HideSelection = true;
            this.txtsdt.IconLeft = null;
            this.txtsdt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsdt.IconPadding = 10;
            this.txtsdt.IconRight = null;
            this.txtsdt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsdt.Lines = new string[0];
            this.txtsdt.Location = new System.Drawing.Point(220, 152);
            this.txtsdt.MaxLength = 32767;
            this.txtsdt.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtsdt.Modified = false;
            this.txtsdt.Multiline = false;
            this.txtsdt.Name = "txtsdt";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsdt.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtsdt.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsdt.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            stateProperties32.ForeColor = System.Drawing.Color.White;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsdt.OnIdleState = stateProperties32;
            this.txtsdt.Padding = new System.Windows.Forms.Padding(3);
            this.txtsdt.PasswordChar = '\0';
            this.txtsdt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtsdt.PlaceholderText = "";
            this.txtsdt.ReadOnly = false;
            this.txtsdt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtsdt.SelectedText = "";
            this.txtsdt.SelectionLength = 0;
            this.txtsdt.SelectionStart = 0;
            this.txtsdt.ShortcutsEnabled = true;
            this.txtsdt.Size = new System.Drawing.Size(260, 39);
            this.txtsdt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtsdt.TabIndex = 13;
            this.txtsdt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtsdt.TextMarginBottom = 0;
            this.txtsdt.TextMarginLeft = 3;
            this.txtsdt.TextMarginTop = 0;
            this.txtsdt.TextPlaceholder = "";
            this.txtsdt.UseSystemPasswordChar = false;
            this.txtsdt.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Calibri", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(99, 158);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(101, 21);
            this.bunifuLabel3.TabIndex = 12;
            this.bunifuLabel3.Text = "Số Điện Thoại:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txttenkh
            // 
            this.txttenkh.AcceptsReturn = false;
            this.txttenkh.AcceptsTab = false;
            this.txttenkh.AnimationSpeed = 200;
            this.txttenkh.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txttenkh.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txttenkh.BackColor = System.Drawing.Color.Transparent;
            this.txttenkh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txttenkh.BackgroundImage")));
            this.txttenkh.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txttenkh.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txttenkh.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txttenkh.BorderColorIdle = System.Drawing.Color.Silver;
            this.txttenkh.BorderRadius = 1;
            this.txttenkh.BorderThickness = 1;
            this.txttenkh.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txttenkh.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txttenkh.DefaultFont = new System.Drawing.Font("Calibri", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txttenkh.DefaultText = "";
            this.txttenkh.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.txttenkh.ForeColor = System.Drawing.Color.White;
            this.txttenkh.HideSelection = true;
            this.txttenkh.IconLeft = null;
            this.txttenkh.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txttenkh.IconPadding = 10;
            this.txttenkh.IconRight = null;
            this.txttenkh.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txttenkh.Lines = new string[0];
            this.txttenkh.Location = new System.Drawing.Point(220, 89);
            this.txttenkh.MaxLength = 32767;
            this.txttenkh.MinimumSize = new System.Drawing.Size(1, 1);
            this.txttenkh.Modified = false;
            this.txttenkh.Multiline = false;
            this.txttenkh.Name = "txttenkh";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttenkh.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txttenkh.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttenkh.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            stateProperties36.ForeColor = System.Drawing.Color.White;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttenkh.OnIdleState = stateProperties36;
            this.txttenkh.Padding = new System.Windows.Forms.Padding(3);
            this.txttenkh.PasswordChar = '\0';
            this.txttenkh.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txttenkh.PlaceholderText = "";
            this.txttenkh.ReadOnly = false;
            this.txttenkh.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txttenkh.SelectedText = "";
            this.txttenkh.SelectionLength = 0;
            this.txttenkh.SelectionStart = 0;
            this.txttenkh.ShortcutsEnabled = true;
            this.txttenkh.Size = new System.Drawing.Size(260, 39);
            this.txttenkh.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txttenkh.TabIndex = 11;
            this.txttenkh.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txttenkh.TextMarginBottom = 0;
            this.txttenkh.TextMarginLeft = 3;
            this.txttenkh.TextMarginTop = 0;
            this.txttenkh.TextPlaceholder = "";
            this.txttenkh.UseSystemPasswordChar = false;
            this.txttenkh.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Calibri", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(83, 97);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(117, 21);
            this.bunifuLabel2.TabIndex = 10;
            this.bunifuLabel2.Text = "Tên Khách Hàng:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtmakh
            // 
            this.txtmakh.AcceptsReturn = false;
            this.txtmakh.AcceptsTab = false;
            this.txtmakh.AnimationSpeed = 200;
            this.txtmakh.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtmakh.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtmakh.BackColor = System.Drawing.Color.Transparent;
            this.txtmakh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtmakh.BackgroundImage")));
            this.txtmakh.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtmakh.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtmakh.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtmakh.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtmakh.BorderRadius = 1;
            this.txtmakh.BorderThickness = 1;
            this.txtmakh.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtmakh.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmakh.DefaultFont = new System.Drawing.Font("Calibri", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtmakh.DefaultText = "";
            this.txtmakh.Enabled = false;
            this.txtmakh.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.txtmakh.HideSelection = true;
            this.txtmakh.IconLeft = null;
            this.txtmakh.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmakh.IconPadding = 10;
            this.txtmakh.IconRight = null;
            this.txtmakh.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmakh.Lines = new string[0];
            this.txtmakh.Location = new System.Drawing.Point(220, 25);
            this.txtmakh.MaxLength = 32767;
            this.txtmakh.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtmakh.Modified = false;
            this.txtmakh.Multiline = false;
            this.txtmakh.Name = "txtmakh";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmakh.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtmakh.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmakh.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmakh.OnIdleState = stateProperties40;
            this.txtmakh.Padding = new System.Windows.Forms.Padding(3);
            this.txtmakh.PasswordChar = '\0';
            this.txtmakh.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtmakh.PlaceholderText = "";
            this.txtmakh.ReadOnly = false;
            this.txtmakh.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtmakh.SelectedText = "";
            this.txtmakh.SelectionLength = 0;
            this.txtmakh.SelectionStart = 0;
            this.txtmakh.ShortcutsEnabled = true;
            this.txtmakh.Size = new System.Drawing.Size(260, 39);
            this.txtmakh.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtmakh.TabIndex = 9;
            this.txtmakh.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtmakh.TextMarginBottom = 0;
            this.txtmakh.TextMarginLeft = 3;
            this.txtmakh.TextMarginTop = 0;
            this.txtmakh.TextPlaceholder = "";
            this.txtmakh.UseSystemPasswordChar = false;
            this.txtmakh.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Calibri", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(86, 31);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(114, 21);
            this.bunifuLabel1.TabIndex = 8;
            this.bunifuLabel1.Text = "Mã Khách Hàng:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnhuy
            // 
            this.btnhuy.AllowAnimations = true;
            this.btnhuy.AllowMouseEffects = true;
            this.btnhuy.AllowToggling = false;
            this.btnhuy.AnimationSpeed = 200;
            this.btnhuy.AutoGenerateColors = false;
            this.btnhuy.AutoRoundBorders = false;
            this.btnhuy.AutoSizeLeftIcon = true;
            this.btnhuy.AutoSizeRightIcon = true;
            this.btnhuy.BackColor = System.Drawing.Color.Transparent;
            this.btnhuy.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnhuy.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnhuy.BackgroundImage")));
            this.btnhuy.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnhuy.ButtonText = "HỦY";
            this.btnhuy.ButtonTextMarginLeft = 0;
            this.btnhuy.ColorContrastOnClick = 45;
            this.btnhuy.ColorContrastOnHover = 45;
            this.btnhuy.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnhuy.CustomizableEdges = borderEdges8;
            this.btnhuy.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnhuy.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnhuy.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnhuy.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnhuy.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnhuy.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnhuy.ForeColor = System.Drawing.Color.White;
            this.btnhuy.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnhuy.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnhuy.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnhuy.IconMarginLeft = 11;
            this.btnhuy.IconPadding = 10;
            this.btnhuy.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnhuy.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnhuy.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnhuy.IconSize = 25;
            this.btnhuy.IdleBorderColor = System.Drawing.Color.White;
            this.btnhuy.IdleBorderRadius = 10;
            this.btnhuy.IdleBorderThickness = 1;
            this.btnhuy.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnhuy.IdleIconLeftImage = null;
            this.btnhuy.IdleIconRightImage = null;
            this.btnhuy.IndicateFocus = false;
            this.btnhuy.Location = new System.Drawing.Point(779, 337);
            this.btnhuy.Name = "btnhuy";
            this.btnhuy.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnhuy.OnDisabledState.BorderRadius = 10;
            this.btnhuy.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnhuy.OnDisabledState.BorderThickness = 1;
            this.btnhuy.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnhuy.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnhuy.OnDisabledState.IconLeftImage = null;
            this.btnhuy.OnDisabledState.IconRightImage = null;
            this.btnhuy.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnhuy.onHoverState.BorderRadius = 10;
            this.btnhuy.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnhuy.onHoverState.BorderThickness = 1;
            this.btnhuy.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnhuy.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnhuy.onHoverState.IconLeftImage = null;
            this.btnhuy.onHoverState.IconRightImage = null;
            this.btnhuy.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnhuy.OnIdleState.BorderRadius = 10;
            this.btnhuy.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnhuy.OnIdleState.BorderThickness = 1;
            this.btnhuy.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnhuy.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnhuy.OnIdleState.IconLeftImage = null;
            this.btnhuy.OnIdleState.IconRightImage = null;
            this.btnhuy.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnhuy.OnPressedState.BorderRadius = 10;
            this.btnhuy.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnhuy.OnPressedState.BorderThickness = 1;
            this.btnhuy.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnhuy.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnhuy.OnPressedState.IconLeftImage = null;
            this.btnhuy.OnPressedState.IconRightImage = null;
            this.btnhuy.Size = new System.Drawing.Size(100, 40);
            this.btnhuy.TabIndex = 12;
            this.btnhuy.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnhuy.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnhuy.TextMarginLeft = 0;
            this.btnhuy.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnhuy.UseDefaultRadiusAndThickness = true;
            this.btnhuy.Click += new System.EventHandler(this.btnhuy_Click);
            // 
            // btnsua
            // 
            this.btnsua.AllowAnimations = true;
            this.btnsua.AllowMouseEffects = true;
            this.btnsua.AllowToggling = false;
            this.btnsua.AnimationSpeed = 200;
            this.btnsua.AutoGenerateColors = false;
            this.btnsua.AutoRoundBorders = false;
            this.btnsua.AutoSizeLeftIcon = true;
            this.btnsua.AutoSizeRightIcon = true;
            this.btnsua.BackColor = System.Drawing.Color.Transparent;
            this.btnsua.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnsua.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnsua.BackgroundImage")));
            this.btnsua.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsua.ButtonText = "SỬA";
            this.btnsua.ButtonTextMarginLeft = 0;
            this.btnsua.ColorContrastOnClick = 45;
            this.btnsua.ColorContrastOnHover = 45;
            this.btnsua.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnsua.CustomizableEdges = borderEdges9;
            this.btnsua.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnsua.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsua.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsua.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsua.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnsua.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnsua.ForeColor = System.Drawing.Color.White;
            this.btnsua.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnsua.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnsua.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnsua.IconMarginLeft = 11;
            this.btnsua.IconPadding = 10;
            this.btnsua.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnsua.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnsua.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnsua.IconSize = 25;
            this.btnsua.IdleBorderColor = System.Drawing.Color.White;
            this.btnsua.IdleBorderRadius = 10;
            this.btnsua.IdleBorderThickness = 1;
            this.btnsua.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnsua.IdleIconLeftImage = null;
            this.btnsua.IdleIconRightImage = null;
            this.btnsua.IndicateFocus = false;
            this.btnsua.Location = new System.Drawing.Point(644, 337);
            this.btnsua.Name = "btnsua";
            this.btnsua.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsua.OnDisabledState.BorderRadius = 10;
            this.btnsua.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsua.OnDisabledState.BorderThickness = 1;
            this.btnsua.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsua.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsua.OnDisabledState.IconLeftImage = null;
            this.btnsua.OnDisabledState.IconRightImage = null;
            this.btnsua.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnsua.onHoverState.BorderRadius = 10;
            this.btnsua.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsua.onHoverState.BorderThickness = 1;
            this.btnsua.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnsua.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnsua.onHoverState.IconLeftImage = null;
            this.btnsua.onHoverState.IconRightImage = null;
            this.btnsua.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnsua.OnIdleState.BorderRadius = 10;
            this.btnsua.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsua.OnIdleState.BorderThickness = 1;
            this.btnsua.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnsua.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnsua.OnIdleState.IconLeftImage = null;
            this.btnsua.OnIdleState.IconRightImage = null;
            this.btnsua.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnsua.OnPressedState.BorderRadius = 10;
            this.btnsua.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsua.OnPressedState.BorderThickness = 1;
            this.btnsua.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnsua.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnsua.OnPressedState.IconLeftImage = null;
            this.btnsua.OnPressedState.IconRightImage = null;
            this.btnsua.Size = new System.Drawing.Size(100, 40);
            this.btnsua.TabIndex = 11;
            this.btnsua.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnsua.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnsua.TextMarginLeft = 0;
            this.btnsua.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnsua.UseDefaultRadiusAndThickness = true;
            this.btnsua.Click += new System.EventHandler(this.btnsua_Click);
            // 
            // btnxoa
            // 
            this.btnxoa.AllowAnimations = true;
            this.btnxoa.AllowMouseEffects = true;
            this.btnxoa.AllowToggling = false;
            this.btnxoa.AnimationSpeed = 200;
            this.btnxoa.AutoGenerateColors = false;
            this.btnxoa.AutoRoundBorders = false;
            this.btnxoa.AutoSizeLeftIcon = true;
            this.btnxoa.AutoSizeRightIcon = true;
            this.btnxoa.BackColor = System.Drawing.Color.Transparent;
            this.btnxoa.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnxoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnxoa.BackgroundImage")));
            this.btnxoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnxoa.ButtonText = "XÓA";
            this.btnxoa.ButtonTextMarginLeft = 0;
            this.btnxoa.ColorContrastOnClick = 45;
            this.btnxoa.ColorContrastOnHover = 45;
            this.btnxoa.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btnxoa.CustomizableEdges = borderEdges10;
            this.btnxoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnxoa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnxoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnxoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnxoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnxoa.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnxoa.ForeColor = System.Drawing.Color.White;
            this.btnxoa.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnxoa.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnxoa.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnxoa.IconMarginLeft = 11;
            this.btnxoa.IconPadding = 10;
            this.btnxoa.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnxoa.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnxoa.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnxoa.IconSize = 25;
            this.btnxoa.IdleBorderColor = System.Drawing.Color.White;
            this.btnxoa.IdleBorderRadius = 10;
            this.btnxoa.IdleBorderThickness = 1;
            this.btnxoa.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnxoa.IdleIconLeftImage = null;
            this.btnxoa.IdleIconRightImage = null;
            this.btnxoa.IndicateFocus = false;
            this.btnxoa.Location = new System.Drawing.Point(509, 337);
            this.btnxoa.Name = "btnxoa";
            this.btnxoa.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnxoa.OnDisabledState.BorderRadius = 10;
            this.btnxoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnxoa.OnDisabledState.BorderThickness = 1;
            this.btnxoa.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnxoa.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnxoa.OnDisabledState.IconLeftImage = null;
            this.btnxoa.OnDisabledState.IconRightImage = null;
            this.btnxoa.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnxoa.onHoverState.BorderRadius = 10;
            this.btnxoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnxoa.onHoverState.BorderThickness = 1;
            this.btnxoa.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnxoa.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnxoa.onHoverState.IconLeftImage = null;
            this.btnxoa.onHoverState.IconRightImage = null;
            this.btnxoa.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnxoa.OnIdleState.BorderRadius = 10;
            this.btnxoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnxoa.OnIdleState.BorderThickness = 1;
            this.btnxoa.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnxoa.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnxoa.OnIdleState.IconLeftImage = null;
            this.btnxoa.OnIdleState.IconRightImage = null;
            this.btnxoa.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnxoa.OnPressedState.BorderRadius = 10;
            this.btnxoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnxoa.OnPressedState.BorderThickness = 1;
            this.btnxoa.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnxoa.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnxoa.OnPressedState.IconLeftImage = null;
            this.btnxoa.OnPressedState.IconRightImage = null;
            this.btnxoa.Size = new System.Drawing.Size(100, 40);
            this.btnxoa.TabIndex = 10;
            this.btnxoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnxoa.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnxoa.TextMarginLeft = 0;
            this.btnxoa.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnxoa.UseDefaultRadiusAndThickness = true;
            this.btnxoa.Click += new System.EventHandler(this.btnxoa_Click);
            // 
            // btnluu
            // 
            this.btnluu.AllowAnimations = true;
            this.btnluu.AllowMouseEffects = true;
            this.btnluu.AllowToggling = false;
            this.btnluu.AnimationSpeed = 200;
            this.btnluu.AutoGenerateColors = false;
            this.btnluu.AutoRoundBorders = false;
            this.btnluu.AutoSizeLeftIcon = true;
            this.btnluu.AutoSizeRightIcon = true;
            this.btnluu.BackColor = System.Drawing.Color.Transparent;
            this.btnluu.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnluu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnluu.BackgroundImage")));
            this.btnluu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnluu.ButtonText = "LƯU";
            this.btnluu.ButtonTextMarginLeft = 0;
            this.btnluu.ColorContrastOnClick = 45;
            this.btnluu.ColorContrastOnHover = 45;
            this.btnluu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnluu.CustomizableEdges = borderEdges11;
            this.btnluu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnluu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnluu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnluu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnluu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnluu.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnluu.ForeColor = System.Drawing.Color.White;
            this.btnluu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnluu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnluu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnluu.IconMarginLeft = 11;
            this.btnluu.IconPadding = 10;
            this.btnluu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnluu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnluu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnluu.IconSize = 25;
            this.btnluu.IdleBorderColor = System.Drawing.Color.White;
            this.btnluu.IdleBorderRadius = 10;
            this.btnluu.IdleBorderThickness = 1;
            this.btnluu.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnluu.IdleIconLeftImage = null;
            this.btnluu.IdleIconRightImage = null;
            this.btnluu.IndicateFocus = false;
            this.btnluu.Location = new System.Drawing.Point(374, 337);
            this.btnluu.Name = "btnluu";
            this.btnluu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnluu.OnDisabledState.BorderRadius = 10;
            this.btnluu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnluu.OnDisabledState.BorderThickness = 1;
            this.btnluu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnluu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnluu.OnDisabledState.IconLeftImage = null;
            this.btnluu.OnDisabledState.IconRightImage = null;
            this.btnluu.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnluu.onHoverState.BorderRadius = 10;
            this.btnluu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnluu.onHoverState.BorderThickness = 1;
            this.btnluu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnluu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnluu.onHoverState.IconLeftImage = null;
            this.btnluu.onHoverState.IconRightImage = null;
            this.btnluu.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnluu.OnIdleState.BorderRadius = 10;
            this.btnluu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnluu.OnIdleState.BorderThickness = 1;
            this.btnluu.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnluu.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnluu.OnIdleState.IconLeftImage = null;
            this.btnluu.OnIdleState.IconRightImage = null;
            this.btnluu.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnluu.OnPressedState.BorderRadius = 10;
            this.btnluu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnluu.OnPressedState.BorderThickness = 1;
            this.btnluu.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnluu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnluu.OnPressedState.IconLeftImage = null;
            this.btnluu.OnPressedState.IconRightImage = null;
            this.btnluu.Size = new System.Drawing.Size(100, 40);
            this.btnluu.TabIndex = 9;
            this.btnluu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnluu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnluu.TextMarginLeft = 0;
            this.btnluu.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnluu.UseDefaultRadiusAndThickness = true;
            this.btnluu.Click += new System.EventHandler(this.btnluu_Click);
            // 
            // btnthem
            // 
            this.btnthem.AllowAnimations = true;
            this.btnthem.AllowMouseEffects = true;
            this.btnthem.AllowToggling = false;
            this.btnthem.AnimationSpeed = 200;
            this.btnthem.AutoGenerateColors = false;
            this.btnthem.AutoRoundBorders = false;
            this.btnthem.AutoSizeLeftIcon = true;
            this.btnthem.AutoSizeRightIcon = true;
            this.btnthem.BackColor = System.Drawing.Color.Transparent;
            this.btnthem.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnthem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnthem.BackgroundImage")));
            this.btnthem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnthem.ButtonText = "THÊM";
            this.btnthem.ButtonTextMarginLeft = 0;
            this.btnthem.ColorContrastOnClick = 45;
            this.btnthem.ColorContrastOnHover = 45;
            this.btnthem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnthem.CustomizableEdges = borderEdges12;
            this.btnthem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnthem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnthem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnthem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnthem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnthem.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnthem.ForeColor = System.Drawing.Color.White;
            this.btnthem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnthem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnthem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnthem.IconMarginLeft = 11;
            this.btnthem.IconPadding = 10;
            this.btnthem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnthem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnthem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnthem.IconSize = 25;
            this.btnthem.IdleBorderColor = System.Drawing.Color.White;
            this.btnthem.IdleBorderRadius = 10;
            this.btnthem.IdleBorderThickness = 1;
            this.btnthem.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnthem.IdleIconLeftImage = null;
            this.btnthem.IdleIconRightImage = null;
            this.btnthem.IndicateFocus = false;
            this.btnthem.Location = new System.Drawing.Point(239, 337);
            this.btnthem.Name = "btnthem";
            this.btnthem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnthem.OnDisabledState.BorderRadius = 10;
            this.btnthem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnthem.OnDisabledState.BorderThickness = 1;
            this.btnthem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnthem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnthem.OnDisabledState.IconLeftImage = null;
            this.btnthem.OnDisabledState.IconRightImage = null;
            this.btnthem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnthem.onHoverState.BorderRadius = 10;
            this.btnthem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnthem.onHoverState.BorderThickness = 1;
            this.btnthem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnthem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnthem.onHoverState.IconLeftImage = null;
            this.btnthem.onHoverState.IconRightImage = null;
            this.btnthem.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnthem.OnIdleState.BorderRadius = 10;
            this.btnthem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnthem.OnIdleState.BorderThickness = 1;
            this.btnthem.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(44)))), ((int)(((byte)(63)))));
            this.btnthem.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnthem.OnIdleState.IconLeftImage = null;
            this.btnthem.OnIdleState.IconRightImage = null;
            this.btnthem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnthem.OnPressedState.BorderRadius = 10;
            this.btnthem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnthem.OnPressedState.BorderThickness = 1;
            this.btnthem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnthem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnthem.OnPressedState.IconLeftImage = null;
            this.btnthem.OnPressedState.IconRightImage = null;
            this.btnthem.Size = new System.Drawing.Size(100, 40);
            this.btnthem.TabIndex = 8;
            this.btnthem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnthem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnthem.TextMarginLeft = 0;
            this.btnthem.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnthem.UseDefaultRadiusAndThickness = true;
            this.btnthem.Click += new System.EventHandler(this.btnthem_Click);
            // 
            // lvds
            // 
            this.lvds.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader1,
            this.columnHeader2,
            this.columnHeader3,
            this.columnHeader4,
            this.columnHeader5});
            this.lvds.FullRowSelect = true;
            this.lvds.GridLines = true;
            this.lvds.Location = new System.Drawing.Point(78, 397);
            this.lvds.Name = "lvds";
            this.lvds.Size = new System.Drawing.Size(957, 240);
            this.lvds.TabIndex = 13;
            this.lvds.UseCompatibleStateImageBehavior = false;
            this.lvds.View = System.Windows.Forms.View.Details;
            this.lvds.Click += new System.EventHandler(this.lvds_Click);
            // 
            // columnHeader1
            // 
            this.columnHeader1.Text = "Mã Khách Hàng";
            this.columnHeader1.Width = 131;
            // 
            // columnHeader2
            // 
            this.columnHeader2.Text = "Tên Khách Hàng";
            this.columnHeader2.Width = 175;
            // 
            // columnHeader3
            // 
            this.columnHeader3.Text = "SDT";
            this.columnHeader3.Width = 162;
            // 
            // columnHeader4
            // 
            this.columnHeader4.Text = "Địa Chỉ";
            this.columnHeader4.Width = 175;
            // 
            // columnHeader5
            // 
            this.columnHeader5.Text = "Loại";
            this.columnHeader5.Width = 125;
            // 
            // frmKhachHang
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(52)))), ((int)(((byte)(54)))));
            this.ClientSize = new System.Drawing.Size(1115, 640);
            this.Controls.Add(this.lvds);
            this.Controls.Add(this.btnhuy);
            this.Controls.Add(this.btnsua);
            this.Controls.Add(this.btnxoa);
            this.Controls.Add(this.btnluu);
            this.Controls.Add(this.btnthem);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmKhachHang";
            this.Text = "frmKhachHang";
            this.Load += new System.EventHandler(this.frmKhachHang_Load);
            this.panel1.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btntracuu;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private System.Windows.Forms.RadioButton rdsinhhoat;
        private Bunifu.UI.WinForms.BunifuTextBox txtdiachi;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox txtsdt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox txttenkh;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txtmakh;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.RadioButton rdsanxuat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnhuy;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnsua;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnxoa;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnluu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnthem;
        private System.Windows.Forms.ListView lvds;
        private System.Windows.Forms.ColumnHeader columnHeader1;
        private System.Windows.Forms.ColumnHeader columnHeader2;
        private System.Windows.Forms.ColumnHeader columnHeader3;
        private System.Windows.Forms.ColumnHeader columnHeader4;
        private System.Windows.Forms.ColumnHeader columnHeader5;
        private Bunifu.UI.WinForms.BunifuTextBox txttimkiem;
    }
}